# Generated by Django 5.1.1 on 2025-03-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=100)),
                ('role', models.CharField(help_text="Student's role or position (e.g. 'Computer Science Student')", max_length=100)),
                ('university', models.CharField(help_text='University name', max_length=100)),
                ('content', models.TextField(help_text='Testimonial content text')),
                ('image', models.ImageField(help_text="Student's photo", upload_to='testimonials/')),
                ('active', models.BooleanField(default=True, help_text='Whether this testimonial is active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
