# Generated by Django 5.2 on 2025-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_program',
            field=models.CharField(blank=True, choices=[('architecture', 'Architecture'), ('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('medicine', 'Medicine'), ('law', 'Law'), ('arts', 'Arts'), ('humanities', 'Humanities'), ('sciences', 'Sciences'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text="User's interests, hobbies, etc.", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="User's biography", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.JSONField(blank=True, default=dict, help_text='Rewards earned by the user', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.JSONField(blank=True, default=dict, help_text='Achievements unlocked by the user', null=True),
        ),
    ]