# Generated by Django 5.2 on 2025-04-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvote_count_cache',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cached upvote count for performance'),
        ),
        migrations.AddField(
            model_name='community',
            name='member_count_cache',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cached member count for performance'),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count_cache',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cached comment count for performance'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote_count_cache',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Cached upvote count for performance'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('social', 'Social'), ('sports', 'Sports'), ('arts', 'Arts & Culture'), ('career', 'Career & Professional'), ('technology', 'Technology'), ('health', 'Health & Wellness'), ('service', 'Community Service'), ('other', 'Other')], db_index=True, default='other', help_text='Category of the community', max_length=20),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the community is private (invite-only)'),
        ),
        migrations.AlterField(
            model_name='communityinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communityinvitation',
            name='invitee_email',
            field=models.EmailField(db_index=True, help_text='Email of the person being invited', max_length=254),
        ),
        migrations.AlterField(
            model_name='communityinvitation',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='communityinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time for events', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Pin this post to the top of the community'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('event', 'Event'), ('announcement', 'Announcement'), ('resource', 'Resource'), ('other', 'Other')], db_index=True, default='discussion', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='communities_post_id_2fd3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_at'], name='communities_post_id_15b736_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='communities_author__a1f82a_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['category', 'is_private'], name='communities_categor_d13d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-created_at'], name='communities_created_54da6c_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['status', 'is_sent'], name='communities_status_23d077_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['community', 'status'], name='communities_communi_b89b36_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['role', 'status'], name='communities_role_8ef590_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['community', 'role'], name='communities_communi_1593fd_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_ecd6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='communities_communi_cd1cef_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', 'post_type'], name='communities_communi_0002a8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-is_pinned', '-created_at'], name='communities_communi_da1b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='communities_author__c34725_idx'),
        ),
    ]
