# Generated by Django 5.2 on 2025-05-08 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_comment_upvote_count_cache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='communities_name_3031a9_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['is_private', '-created_at'], name='communities_is_priv_0b60f4_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['requires_approval'], name='communities_require_067290_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', 'author'], name='communities_communi_93b787_idx'),
        ),
    ]
