# Generated by Django 5.2 on 2025-05-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_communities_name_3031a9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for this post', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('members', 'Members Only - Visible only to community members'), ('admin', 'Admin Only - Visible only to community admins')], db_index=True, default='public', help_text='Who can see this post', max_length=20),
        ),
    ]
