# Generated by Django 5.2 on 2025-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_post_tags_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags for this post', max_length=255),
        ),
    ]
